name = "react-ppr-workers"
main = "./dist/cloudflare/worker.js"
compatibility_date = "2024-10-10"
compatibility_flags = ["nodejs_compat"]

assets = { directory = "./dist/client", binding = "CLIENT" }

workers_dev = true

routes = [
  {pattern = "react-ppr-workers.carlssonk.com", custom_domain = true }
]

[env.dev]
vars = { ENVIRONMENT = "development" }
[env.production]
vars = { ENVIRONMENT = "production" }